language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- ./create_config.sh
script:
- npm test
notifications:
  hipchat:
    rooms:
      secure: hJXg+h3aGEAKsNlyDHw9eUc27vdbL5Dco+2ZllNNqP2EFrSIC29qhVBhSc+dd42GSb/oYToeKDS5zYXiXK7TL7esbBRLWjgwx0VAzAdZBnFGwHglzAxwfB1j4EW56DnAw4XbUtAER1R6tXNidhqMt61bBmCdqcSBNaISUaC0IS0=
    template:
    - ! '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a>/<a
      href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
env:
  global:
    - secure: "TgWVbzuQix6V+YEkOOYjCs4CSzRHUuTgpbSdGkjh9GgwrZmRV2b9glTuHNSeceYWWeeja9WTIBHP0CZyQ424Ky1bEijrkgtIjhxlRlieEZKuMIkeEjxYQUVRy7hCmQsDkPGYjgEqI+vuyIQK6eg7ycw3XygUqkcZjB2htsnbGxY="
    - secure: "iB5MKg6hj34ruWLRPnzD8c9cQ5FcGc6cimOvwNpLw+W7U7boWVwLMxBb+9WOqECWTKnj59Seoew4zga2guJ3NACQTJpmt2z/0KGD58zzmcrTLDpoDnTjB+0cJnFUkcRMq2DhiGAN/1uM+Hlhix3VkGiZqWI37uDXGcdw4QNoN/A="
    - secure: "CAecgKjLZXxDp68ohd+/Ejm1zG98e3hUYWYpBvrpNz3Scasyr4KVDcg3u8c0wA3kwJbeMHuqVR62ybZ7YP91VMmMr+4UCT/eDkhIYKwVx6A/oo7t8FrfcxgoI0nNlKoWLgBmXr/lR1x1MMpQflj3rkuBJsSD9HcUdYannzNHleY="
    - secure: "DagkvoCuZKi31ah6M6jZDevnskDh4Hya1wN2f3/iZgqqaiCrtryq3BxXZUtz8uImD0iMnXKfzmb089JreVfECM9X4EO/TDVT7xK8YYj8ujBYncrcgmCqi79xOxZ+lekBAghOLXR228tndZLLUWz2uIOAdL2MwMJXukmAlvMoZ7c="
    - secure: "DyCKqmAxpSDbJdFe9KHCVg4oeZKpiZspBS8d6Ne0wILKSzZ2jDNsUO5zrGViGRuU9YWE3+Z+Vyt+EvtOJElxABwSBHwU7yGQHSPNBxwsG+3mjdYJai8rT9FQ8z+dsCy3we9Fy/Jy2CH717bjFgzhCqr1wMEQTjhZgeNNkXU3JV8="
    - secure: "IKPTxsGg/AHVPVguRck2stJ1d2O+vfULyPt6N8nXF6jKSZrX+BBDdDpqEFyv7jfaHKey6aLbYfkJEhka+cWFeZNBbf+TlWPhEJLAbQzn3Z2H8ITCLHSScNEXvasBM8zTLIobLDmz/2mK0GWr4H/xC8Q7HOsqVk5kaHFUhn/3/aA="
